#!/bin/bash
set -e

cat .io.livecode.ch/header.txt $1 .io.livecode.ch/footer.txt >out.ml
if [ -s $2 ]
then
    mv $2 extra.ml
else
    touch extra.ml
fi
cat extra.ml out.ml >program.ml

ocaml program.ml
